### ISSUE TITLE
use MathX.DistanceSqr instead of MathX.Distance

### ISSUE THREAD

**Issue by art0007i** [Nytra/ResoniteDistantComponentOptimizer#1]
allegedly this improves performance. if you look at the code for Distance it just calculates DistanceSqr and passes it into Sqrt so you avoid that sqrt. of course you need to square the other side of the equation but I think multiplication is more efficient than sqrt

https://github.com/Nytra/ResoniteDistantComponentOptimizer/blob/main/DistantComponentOptimizer/BasicPatcher.cs#L34

**Comment by Nytra** [comment]
well sqrt is just raising it to the 0.5 power, rather than the 2 power for sqr

would be interesting to test if one is actually faster than the other

**Comment by art0007i** [comment]
mathematically it is, but a computer does not simply "raise to a power". squaring a number is multiplying it by itself, sqrt is a little more complex

**Comment by Nytra** [comment]
Fixed https://github.com/Nytra/ResoniteDistantComponentOptimizer/releases/tag/1.0.1
