### ISSUE TITLE
Respawning is broken.

### ISSUE THREAD

**Issue by BlueTera** [Nytra/ResoniteDistantComponentOptimizer#2]
This mod is broken if you re-spawn it will re-spawn everyone else in a loop until there is only one left. And break multiple other things.

**Comment by Nytra** [comment]
I believe this is now fixed https://github.com/Nytra/ResoniteDistantComponentOptimizer/releases/tag/1.0.2

I have tested this in my headless and with another user, respawning no longer breaks things
