### ISSUE TITLE
Config option to not use userscale for distance calculation

### ISSUE THREAD

**Issue by LeCloutPanda** [Nytra/ResoniteDistantComponentOptimizer#3]
Having this will allow users to be smaller and not have people right in front of them look choppy

**Comment by Zetaphor** [comment]
As someone who regularly scales this change would be greatly appreciated!

**Comment by Nytra** [comment]
This has now been committed to master, I just haven't made a release yet

**Comment by Nytra** [comment]
Released https://github.com/Nytra/ResoniteDistantComponentOptimizer/releases/tag/1.1.0
